### ISSUE TITLE
emulator

### ISSUE THREAD

**Issue by konsumer** [langolierz/r_e_c_u_r#152]
Hi, I made a simple lil script to send "knobs" to glslViewer, for shader-dev. It's very handy, since the uniforms are all the same, and you can use webcam or video-files with it, and it updates on save.

![image](https://github.com/user-attachments/assets/44ceda44-c210-422e-85da-a73d89a9ce19)

Feel free to use it directly here, or link to it, if you want:

https://github.com/konsumer/glsl_sandbox

**Comment by cyberboy666** [comment]
so cool - thank you very much for this ! i will add links in shader dev wiki page

**Comment by konsumer** [comment]
I am working on a [web-based version](https://github.com/konsumer/recurweb) to simplify installation (no need for python, glsviewer, etc on host, just go to a web-page.) I will update here when it's working.

**Comment by konsumer** [comment]
Ok, I have [this](https://konsumer.js.org/recurweb/) setup. I am still trying to troubleshoot video-textures, but it works great with still images.

You can also link to any "raw" gist link like [this](https://konsumer.js.org/recurweb/#konsumer/c2c1045d7040a2eceef3a73242abcb92/raw/3c6fe9e0d13bf9f399ad0b231a5cbde181dd4092/wobble.frag)

**Update:** I wrote my own preview-thing, and now video is also working great. There may still be things off with uniforms (like no `v_texcoord`, but `gl_FragCoord.xy` obviously works fine, and can be used in it's place.) I couldn't get it working, and sort of figured it might just be better to use the standard input `gl_FragCoord` for example. It seems like all the shaders work fine.

I went through all the shaders and converted them to use the standard stuff, fixed formatting, and tried to add meta-info to top (author, title) [here](https://github.com/konsumer/glsl_sandbox/tree/main/shaders). I also added a few new ones (my [chromakey](https://github.com/konsumer/glsl_sandbox/blob/main/shaders/2-input/chromakey.frag) is pretty nice, for example.) Should I PR those here @cyberboy666 ? Do you have any advice for setting up my vert-shader/threejs code to make it match this repo's uniforms better?
