### ISSUE TITLE
make a dotfiles directory

### ISSUE THREAD

**Issue by leobrowning92** [langolierz/r_e_c_u_r#28]
The purpose of a dotfiles directory being to document the necessary configuration changes made to the pi in order to run the project.

The directory can include the actual config files such as 
    
-.remap
-launcher.sh
-.config/xdg/lxsessions.....autostart
-drivers for the screen
-python packages necessary for installation

**Comment by leobrowning92** [comment]
done here #30 but the necessary files still need to be added to the folder, and then the readme needs to be updated to detail how and when those files get used.

**Comment by langolierz** [comment]
this is pretty much done - can probably be updated/tested while working on issue #16
