### ISSUE TITLE
add git integration

### ISSUE THREAD

**Issue by ben-caldwell** [langolierz/r_e_c_u_r#52]
- display branch name in title
- action to pull latest version/switch branch

**Comment by langolierz** [comment]
i added a basic version of this in the new (c_o_n_j_u_r) branch. it just tries a git pull (warns if you are not on a network) , and then resets if it gets anything new (and re-compiles the openframework app if that gets anything new),

the only issue i can think of at the moment regarding this is:
- if you have made any changes ie mapped your midi different, the pull will fail, (you should just do the pull yourself from cmdline? first stash your changes, then pull then stash pop ? and maybe sort out merge conflicts ?) maybe i should document that somewhere... then close this ?
