### ISSUE TITLE
need to configure the pi to run on boot

### ISSUE THREAD

**Issue by langolierz** [langolierz/r_e_c_u_r#7]

**Comment by leobrowning92** [comment]
Wanted to set things up to autostart after xdg got going, there are a number of ways of tackling this, mentioned [here](https://www.raspberrypi-spy.co.uk/2014/05/how-to-autostart-apps-in-rasbian-lxde-desktop/).

we ended up using method 2 from that page, which is _user specific_ and involves editing the autostart config file:

    sudo nano ~/.config/lxsession/LXDE/autostart

and adding the following line to the bottom of the file:

    @bash /path/to/launch/bash/launchscript.sh
