### ISSUE TITLE
Setting PAL / NTSC doesn't seem to work from menu

### ISSUE THREAD

**Issue by hacklab01** [langolierz/r_e_c_u_r#81]
Here's me bugging you again. =D

I needed to switch video modes to force it into PAL, and it looks like the switch from the menu does nothing. Needed to go into /boot/config.txt and set it manually (nothing was edited / added to the file after changing the setting).

**Comment by langolierz** [comment]
Thanks for the bug reports; i appreciate it. This use to work. I wonder
what has changed. Will take a look into it

**Comment by langolierz** [comment]
Im not sure if i ever got around to reproducing this altgough other people on the group also reported it . Anyway i think its fixed now. If no one else reports it i will close
