### ISSUE TITLE
new display mode : shader_launcher

### ISSUE THREAD

**Issue by langolierz** [langolierz/r_e_c_u_r#94]
functionally the same as the SAMPLER mode, but for shaders, ie you can map a shader_file to a bank/slot from the shader_browser (maybe by pressing FN + SQUARE), and then launch corresponding shaders with the num keys, same keys for next page etc ...

... would also be nice if these shaders were in a different 'node' to the Fn + 6 shaders so there was more options for chaining them etc ...

**Comment by ParticlesIntoWaves** [comment]
I almost see this as being added to the sampler playlist so I can switch between video clips and shaders seamlessly. And being able to call them up the same as video clips would be nice. 

In addition to this it would be nice to be able to have a playlist of FX shaders that can also easily be switched. You could process a video feed (or clip) with a curated bunch of alternating FX either with manual key switching, MIDI, or even a fixed length!
